#ifndef DEVICES_NEWSTYLE_H
#define DEVICES_NEWSTYLE_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#define NSCMD_DEVICEQUERY 0x4000

struct NSDeviceQueryResult {
	ULONG  DevQueryFormat;
	ULONG  SizeAvailable;

	UWORD  DeviceType;
	UWORD  DeviceSubType;
	UWORD *SupportedCommands;
};

enum {
	NSDEVTYPE_UNKNOWN = 0,
	NSDEVTYPE_GAMEPORT,
	NSDEVTYPE_TIMER,
	NSDEVTYPE_KEYBOARD,
	NSDEVTYPE_INPUT,
	NSDEVTYPE_TRACKDISK,
	NSDEVTYPE_CONSOLE,
	NSDEVTYPE_SANA2,
	NSDEVTYPE_AUDIO,
	NSDEVTYPE_CLIPBOARD,
	NSDEVTYPE_PRINTER,
	NSDEVTYPE_SERIAL,
	NSDEVTYPE_PARALLEL
};

#ifndef NSCMD_TD_READ64

#define NSCMD_TD_READ64    0xC000
#define NSCMD_TD_WRITE64   0xC001
#define NSCMD_TD_SEEK64    0xC002
#define NSCMD_TD_FORMAT64  0xC003

#define NSCMD_ETD_READ64   0xE000
#define NSCMD_ETD_WRITE64  0xE001
#define NSCMD_ETD_SEEK64   0xE002
#define NSCMD_ETD_FORMAT64 0xE003

#endif /* NSCMD_TD_READ64 */

#endif /* DEVICES_NEWSTYLE_H */
